### ISSUE TITLE
为什么这么大。。。。。

### ISSUE THREAD

**Issue by buluojava** [m-damavandi/Android-VLC-Sample#1]
这个库对APP来说真的太大了，能不能缩小一点呢？

**Comment by m-damavandi** [comment]
this lib contain native lib that cause increase apk size, you can build app on separate cpu arch support.
app size : arm7 ~ 11mb
app size : universal ~ 40mb!

**Comment by buluojava** [comment]
May I ask if you can support the screenshots and videos ？

**Comment by m-damavandi** [comment]
you can get screenshot from textureview
